### ISSUE TITLE
multi sign wallet electrum network not connected

### ISSUE THREAD

**Issue by yangchunhe** [akhavr/electrum-dash#102]
multi sign wallet electrum network not connected, but Single signature is normal

**Comment by yangchunhe** [comment]
this is log:
20200205T024225.144060Z |     INFO | network | connecting to xxxx:50002:s as new interface
20200205T024225.408402Z |     INFO | interface.[xxxx:50002] | connection established. version: ['ElectrumX 1.14.0', '1.4']
20200205T024225.448774Z |     INFO | interface.[xxxx:50002] | set blockchain with height 1216181
20200205T024225.450070Z |     INFO | interface.[xxxx:50002] | skipping header 1216181
20200205T024225.451374Z |     INFO | network | switching to xxxx:50002:s
20200205T024225.468514Z |     INFO | verifier.[signxx] | requested merkle 
20200205T024225.533281Z |     INFO | network | fee_histogram []
20200205T024225.533655Z |     INFO | network | fee_estimates {25: 1000, 10: 1000, 5: 1000, 2: 1000}
20200205T024225.536825Z |     INFO | verifier.[signxxx] | 
20200205T024226.039415Z |     INFO | interface.[xxxx:50002] | disconnecting due to GracefulDisconnect(InnerNodeOfSpvProofIsValidTx(),)

**Comment by zebra-lucky** [comment]
Cause of the problem is a false positive on "Leaf-Node Vulnerability" attack. Same as in #102

Trying found a solution on this problem.

**Comment by akhavr** [comment]
@yangchunhe let me know if you're still experiencing the issue.  Closing now.
