### ISSUE TITLE
PrivateSend on imported wallets

### ISSUE THREAD

**Issue by vrobolab** [akhavr/electrum-dash#114]
Hello, I can't use Privatesend on imported wallet, app says that PrivateSend is supported on "standard-bip32" wallet type. Could you make Privatesend for imported wallets in the future?

**Comment by akhavr** [comment]
No, this isn't possible since you import individual private keys into the imported wallet and there's no way to consistently create new keys out of this set.

Best way is to sweep those funds into a fresh bip32 wallet and mix them there.
