### ISSUE TITLE
Request for package with dependencies

### ISSUE THREAD

**Issue by estevaocm** [akhavr/electrum-dash#12]
Hello, it would be nice if a release package including python dependencies was provided, as the original Electrum, Electrum-LTC and Electron Cash do nowadays. I get several compilation problems in my Debian Jessie for https://github.com/estevaocm/bitkey

**Comment by akhavr** [comment]
Starting from 3.0.6.1 we've got all dependencies in `packages`, but `x11-hash` which is platform specific.

We have `x11-hash-py` on our todo list, but it's not going to happen soon.
