### ISSUE TITLE
Electrum network not connected error

### ISSUE THREAD

**Issue by eltNEG** [akhavr/electrum-dash#126]
I am using the latest version of dash electrum (v 3.3.8.6). I upgraded to the new version because the old version didn't connect to electrum servers. The error occurs on both testnet and livenet.

How can this be fixed?

<img width="1017" alt="Screenshot 2020-08-01 at 12 19 41 PM" src="https://user-images.githubusercontent.com/22221987/89100725-4f587e00-d3f1-11ea-851f-cad577dad0c4.png">

**Comment by zebra-lucky** [comment]
Fixed testnet server problem, you can try if it works now.

**Comment by eltNEG** [comment]
I can confirm that it works. Thanks.

**Comment by akhavr** [comment]
@eltNEG also consider using tor, there are more testnet servers there.

Closing
