### ISSUE TITLE
Right mouse clicking certain fields crashes the 'watching only' type wallet

### ISSUE THREAD

**Issue by qwizzie** [akhavr/electrum-dash#128]
Type wallet : Imported watching only wallet, maybe applicable on default wallet type as well (i can not test that right now)
Dash Electrum Windows Version 3.3.8.6
OS : Windows 10, 64bit

Crash can be observed occurring when doing the following actions 

Tools - Preferences - Fiat 

Fiat currency Eur or BTC 
Show history rates : selected
Show capital gains in history : selected
Show Fiat balances for addresses : selected

Source : Coingecko

Left mouse click a transaction and right mouse click on field Eur/BTC Acquisition price or right mouse click Eur/BTC Capital Gains
Result : crash

Also both Eur/BTC Acquisition price field and Eur/BTC Capital Gains field do not have a value, regardless if tor proxy is on or off. Both fields stay empty.

**Comment by akhavr** [comment]
To be fixed in #130 and #132
