### ISSUE TITLE
Ledger Nano S warning: Derivation path is unusual: derivation path 44

### ISSUE THREAD

**Issue by cloudwheels** [akhavr/electrum-dash#141]
With ledger nano S, I have the warning message "Derivation path is unusual: derivation path 44'". 

I'm running Dash electrum 3.3.8.7 but also occurred on 3.3.8.5 and I believe this happened since I used the device with ledger live and it forced upgrade to firmware 1.6.1 (dash app 1.4.7).

This issue is mentioned in their docs here https://support.ledger.com/hc/en-us/articles/360015739499 (for nano s) and here (for nano x but with a bit more detail on the issue) https://support.ledger.com/hc/en-us/articles/360015738179

You will see from the second link it's related to "a vulnerability in the Bitcoin derivative apps" and their recommended solution/fix is ledger bitcoin app > 1.4.6 (I have 1.4.7)

I decided that I was happy enough to accept the path, because it's not asking me to sign anything etc, but the next step after that is it gives me an address to approve. I'm not sure about the consequences of doing that!

When I reject that address, the error in electrum is "Exception : Invalid status 6985".

A similar issue can be found in the main electrum repo.  The comments in this PR/ issue suggest that it may relate only to the path dervied for file encryption https://github.com/spesmilo/electrum/pull/6512#issuecomment-677643302

**Comment by cloudwheels** [comment]
Please see answers from (the very authoritative) btchip here:
https://www.reddit.com/r/ledgerwallet/comments/ihjfoh/derivation_path_is_unusual_warning_with_dash/g31quq6?utm_source=share&utm_medium=web2x&context=3

Basically it's ok to accept and continue with both the path and the address. I confirm that after doing this 3 times I was able to load the wallet successfully. The issue should be dealt with on the Ledger side in a future release.

**Comment by zebra-lucky** [comment]
Watching on upstream pull request:
https://github.com/spesmilo/electrum/pull/6512

**Comment by zebra-lucky** [comment]
> Bitcoin application 1.4.8 has been deployed and should fix this issue

On 1.4.8 it seems the problem is not emerges

**Comment by akhavr** [comment]
@cloudwheels closing issue now.  Create a new one and mention #141 if the problem emerges again.
