### ISSUE TITLE
Create denominations transactions combine inputs from multiple addresses

### ISSUE THREAD

**Issue by Antti-Kaikkonen** [akhavr/electrum-dash#142]
Dash Electrum create denominations transactions ("PS New Denoms") combine inputs from multiple addresses.

This is not good because it associates the addresses with the same user and can also make multi-input PrivateSend transactions more traceable. Attacks like the [cluster intersection attack](https://arxiv.org/pdf/1709.02489.pdf) rely on all PrivateSend inputs being traceable to the same address cluster.

Dash core wallet also used to combine inputs from multiple addresses but it was changed years ago. To avoid timing correlation I think it would be even better if a random delay is added between create denominations transactions that use inputs from different addresses.

**Comment by zebra-lucky** [comment]
> I think it would be even better if a random delay is added between create denominations transactions that use inputs from different addresses.

Random delay between 30-300 sec is ok?

**Comment by Antti-Kaikkonen** [comment]
> > I think it would be even better if a random delay is added between create denominations transactions that use inputs from different addresses.
> 
> Random delay between 30-300 sec is ok?

I don't know if it would slow down mixing too much. But most importantly create denominations transactions should have only 1 input address.

**Comment by zebra-lucky** [comment]
Seems there is need to use change values less of 10000 (collateral value) as fee.
If ~2 Dash of 3 Dash utxo is denominated, then rest is placed to change.
If rest is small and can not be used for collateral or denoms then it should be spent as fee.

**Comment by zebra-lucky** [comment]
And additionally new collateral txins also need get by addresses.

**Comment by Antti-Kaikkonen** [comment]
> Seems there is need to use change values less of 10000 (collateral value) as fee.
> If ~2 Dash of 3 Dash utxo is denominated, then rest is placed to change.
> If rest is small and can not be used for collateral or denoms then it should be spent as fee.

Why is spending the small change necessary? Dash core does not do this as far as I know but I'm not 100% sure.

> And additionally new collateral txins also need get by addresses.

I agree. 

Also I have an idea: I don't think that dash core does this, but I think it could make sense to create collateral inputs from mixed outputs when they are available to prevent people from observing in the blockchain when someone is actively mixing. Obviously this is not possible for the first collateral inputs because mixed outputs are not available.

Have you considered using a different derivation path for mixing to better separate mixing activity from regular transactions? I think that washabi and samurai wallets use a premix -> mix -> postmix wallet structure but again I'm not 100% sure.

**Comment by zebra-lucky** [comment]
> Why is spending the small change necessary? Dash core does not do this as far as I know but I'm not 100% sure.

If it left as a change then it can be denominated only with some other coins from
other addresses (disabled), or if funds arrive on same address again. Or it can be
spent by regular transaction with some other coins from other addresses again.

**Comment by zebra-lucky** [comment]
> Have you considered using a different derivation path for mixing to better separate mixing activity from regular transactions? I think that washabi and samurai wallets use a premix -> mix -> postmix wallet structure but again I'm not 100% sure.

Currently is separate derivations for PS denoms/collateral and for collateral change (2 derivations).

**Comment by zebra-lucky** [comment]
> Also I have an idea: I don't think that dash core does this, but I think it could make sense to create collateral inputs from mixed outputs when they are available to prevent people from observing in the blockchain when someone is actively mixing. Obviously this is not possible for the first collateral inputs because mixed outputs are not available.

Maybe it make sense, but question on change arises again.
To not return change on denom address it is possible to create collateral
value on 90000 value from 100001 denoms and rest place to fee.

**Comment by zebra-lucky** [comment]
Updated changes in #175

**Comment by zebra-lucky** [comment]
#175 is merged and go in release 4.0.9.2

New GUI option "Group origin coins by address" is added (off by default).

<img src="https://user-images.githubusercontent.com/992125/108517484-28e82a80-72d0-11eb-898f-509b6671204b.png" width="512">

<img src="https://user-images.githubusercontent.com/992125/108517489-2980c100-72d0-11eb-8a5a-654d049db8bb.png" width="256">

**Comment by zebra-lucky** [comment]
Mix origins (coins used in new denoms/collateral workflows) is grouped by address
as inputs to new denoms/new collaterals.

Additionally random delay between new denom workflows is added.

Need to test, possibly some behaviour is unusual (mix origin coins is tracked,
and trying not to be used as input for transactions other than new denoms/new collateral.

**Comment by akhavr** [comment]
@Antti-Kaikkonen please, run test on a testnet and let us know how this works.  Closing the issue, so far.
