### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [akhavr/electrum-dash#147]
https://f-droid.org/wiki/index.php?title=org.dash.electrum.electrum_dash/lastbuild_303080701&oldid=282211

I tried to add that dep, then another, then another, then it started asking for a lot of deps.

**Comment by akhavr** [comment]
Now we're finalizing update to 4.0.4 upstream version.  When this will be completed (RSN), we'll proceed to builds on all supported platforms and stores, including f-droid.
