### ISSUE TITLE
Error build-electrum-git.sh

### ISSUE THREAD

**Issue by expert-soft** [akhavr/electrum-dash#16]
Hello.
uname -r
4.13.0-36-generic
uname -a
 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
python -V
Python 2.7.12

sudo apt-get install python-setuptools
sudo apt-get install python-dev
sudo apt-get install libusb-dev
sudo apt-get install libudev-dev
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install pyqt4-dev-tools
sudo apt-get install protobuf-compiler
sudo apt-get install python-pycurl gettext
sudo apt-get install python-pip
sudo apt-get install wine

sudo git clone https://github.com/akhavr/electrum-dash.git
cd electrum-dash

sudo python setup.py install
sudo pyrcc4 icons.qrc -o gui/qt/icons_rc.py
sudo protoc --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto

sudo ./contrib/make_locale
sudo pip install .
sudo ./contrib/make_packages

cd contrib/build-wine/
sudo ./prepare-wine.sh
sudo ./prepare-hw.sh
sudo ./build-electrum-git.sh

Clone
Cloning into 'electrum-git'...
remote: Counting objects: 43713, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 43713 (delta 0), reused 1 (delta 0), pack-reused 43709
Receiving objects: 100% (43713/43713), 20.63 MiB | 18.26 MiB/s, done.
Resolving deltas: 100% (31816/31816), done.
Checking connectivity... done.
Last commit: 3.0.3-530-g79edd2d
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
fixme:msvcrt:__clean_type_info_names_internal (0x61050830) stub
fixme:msvcrt:__clean_type_info_names_internal (0x672561c0) stub
fixme:msvcrt:__clean_type_info_names_internal (0x61050830) stub
fixme:msvcrt:__clean_type_info_names_internal (0x672561c0) stub
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
196 INFO: Testing for ability to set icons, version resources...
250 INFO: ... resource update available
255 INFO: UPX is not available.
302 INFO: Processing hook hook-os
502 INFO: Processing hook hook-time
524 INFO: Processing hook hook-cPickle
625 INFO: Processing hook hook-_sre
838 INFO: Processing hook hook-cStringIO
973 INFO: Processing hook hook-encodings
992 INFO: Processing hook hook-codecs
Traceback (most recent call last):
  File "C:/pyinstaller/pyinstaller.py", line 18, in <module>
    run()
  File "C:\pyinstaller\PyInstaller\main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "C:\pyinstaller\PyInstaller\main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "C:\pyinstaller\PyInstaller\build.py", line 1924, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\pyinstaller\PyInstaller\build.py", line 1873, in build
    execfile(spec)
  File "deterministic.spec", line 52, in <module>
    runtime_hooks=['pyi_runtimehook.py'])
TypeError: __init__() got an unexpected keyword argument 'datas'
fixme:msvcrt:__clean_type_info_names_internal (0x1600ff0) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e3b304c) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e8d8088) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e7ba8c4) stub
fixme:msvcrt:__clean_type_info_names_internal (0x90c4b0) stub
fixme:msvcrt:__clean_type_info_names_internal (0x44ca30) stub
fixme:msvcrt:__clean_type_info_names_internal (0x100f0610) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1d1b6210) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e26e980) stub

**Comment by elmora-do** [comment]
seems the pyinstaller version used by the script doesn't have the datas parameter defined in the Analysis class, I added it in build.py:370 and the error is gone, however I can't compile the windows version yet

**Comment by elmora-do** [comment]
- I used this version of pyinstaller and I can skip the error also `https://github.com/ecdsa/pyinstaller/archive/fix_2952.zip`
- Change the command used in build-electrum-git.sh `wine "C:/Python27/scripts/pyinstaller.exe" --noconfirm --ascii --name $NAME_ROOT-$VERSION -w deterministic.spec`
- I hard coded the values of every script in deterministic.spec,` a = Analysis(['electrum-dash']` to `a = Analysis(['/the/whole/path/electrum-dash']`
- Doing that I can get the installer, however I'm not able to run the wallet, when I click on the exe nothing happen.
- If I run the console.exe I got this 
![image](https://user-images.githubusercontent.com/2745076/38282860-05268ff6-3778-11e8-914c-913b2b72eb3f.png)

**Comment by akhavr** [comment]
Have you tried scripts, we use for travis builds?  They work for us, since we're releasing windows version using them.  Reopen, if this is still an issue.
