### ISSUE TITLE
cannot import name 'ProxyConnector' from 'aiohttp_socks'

### ISSUE THREAD

**Issue by molecular** [akhavr/electrum-dash#162]
my system had a python upgrade to 3.9 so I reinstalled virtual python environment for electrum-dash using contrib/deterministic-build/* requirement files.

this then happens on master and 4.0.4.1 when I try to start electrum-dash:

```
/home/nick/bitcoin/electrum-dash/packages/aiohttp/helpers.py:105: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
Traceback (most recent call last):
  File "/home/nick/bitcoin/electrum-dash/./electrum-dash", line 83, in <module>
    from electrum_dash.logging import get_logger, configure_logging
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/__init__.py", line 15, in <module>
    from .util import format_satoshis
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/util.py", line 50, in <module>
    from aiohttp_socks import ProxyConnector, ProxyType
ImportError: cannot import name 'ProxyConnector' from 'aiohttp_socks' (/home/nick/bitcoin/electrum-dash/packages/aiohttp_socks/__init__.py)
```

not sure if I'm doing something wrong or this is a mistmatch in requirements?

**Comment by molecular** [comment]
this fixed it:

```
#> pip install -t packages --upgrade -r contrib/deterministic-build/requirements-hw.txt
#> pip install -t packages --upgrade -r contrib/deterministic-build/requirements-binaries.txt
#> pip install -t packages --upgrade -r contrib/deterministic-build/requirements.txt
```

without "-t packages" didn't help. Without "--upgrade" didn't help

**Comment by molecular** [comment]
another remark.

when installing dependencies from contrib/deterministic-build/requirements.txt I get:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    python-socks[asyncio]>=1.0.1 from https://files.pythonhosted.org/packages/b7/ce/82275ff2528b2ca3dfd397863005a79c35c832e11e0b85fce723c4ec0da7/python_socks-1.1.2-py3-none-any.whl#sha256=4390882760ae60b14615f951aac3ef2e9eab45eb33ed8e7ed02d9b4dfb3b5640 (from aiohttp-socks==0.5.5->-r contrib/deterministic-build/requirements.txt (line 15))
```

**Comment by zebra-lucky** [comment]
> another remark.
> 
> when installing dependencies from contrib/deterministic-build/requirements.txt I get:
> 
> ```
> ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
>     python-socks[asyncio]>=1.0.1 from https://files.pythonhosted.org/packages/b7/ce/82275ff2528b2ca3dfd397863005a79c35c832e11e0b85fce723c4ec0da7/python_socks-1.1.2-py3-none-any.whl#sha256=4390882760ae60b14615f951aac3ef2e9eab45eb33ed8e7ed02d9b4dfb3b5640 (from aiohttp-socks==0.5.5->-r contrib/deterministic-build/requirements.txt (line 15))
> ```

try to add `--no-dependencies` to pip args
