### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [akhavr/electrum-dash#163]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by zebra-lucky** [comment]
Thanks!
Will be added in the next release.

**Comment by zebra-lucky** [comment]
Built 4.0.9.1 with screenshots:
https://f-droid.org/en/packages/org.dash.electrum.electrum_dash/
