### ISSUE TITLE
Does not sync at all

### ISSUE THREAD

**Issue by venomone** [akhavr/electrum-dash#164]
hey folks,

im running out of ideas, my wallet is not syncing anymore. I already tried it from my server at the datacenter, on my laptop, on my workstation, on windows, linux etc. Non of them gets sync, electrum-dash simply gets stuck for some reason.
I can also not relate this issue to anything on my network as I tried completly diffrent ones (Home and DC). Does smb has any idea what I can try next? Very frustating :(

Kind regards and thanks in advance

**Comment by venomone** [comment]
The only way for me to get electrum-dash to a synced state is using a Tor proxy which is not what I wanted to do.

**Comment by akhavr** [comment]
What OS are you using?

If you hit the connection icon in the bottom right corner, what servers do you see online?

**Comment by akhavr** [comment]
Reopen if it's still an issue.
