### ISSUE TITLE
Deposit doesn´t arrive

### ISSUE THREAD

**Issue by doctor973** [akhavr/electrum-dash#165]
Hi guys, Ive made a deposit to may electrum dash wallet but it did not arrive, although the transaction is confirmed:
Trasaction ID 612f4f745c4282ebba97f4b8d31148f27c1c14518a7ff1cccbd5f5d109e5d315
I updated my wallet, but no transaction appeared. I even deleted and reinstalled my wallet, but with no results.
Any ideas?

**Comment by akhavr** [comment]
Did you send ~1.28Dash to multisig `7koqicc8CjNDzF98ZKvpomvEr2C2hpLweC` ?

**Comment by doctor973** [comment]
Hi and thanks for answering.
But I must apologise; it was my fault! It was not the transaction ID I posted. It was another transaction that was not confirmed (fault of the sender!!!). So forget the issue and if you can, delete the thread!!

Thanks
________________________________
