### ISSUE TITLE
Dash Electrum May Be Broadcasting Rather than Sending Signed Transaction to Processor (BIP70)

### ISSUE THREAD

**Issue by TheDerrickJ** [akhavr/electrum-dash#174]
Recently Anypay missed a payment on eGifter from a customer who reported he was using Dash Electrum. That confused me because I believe that should be impossible. The way I understand the BIP70 protocol to work is:

1) The payment processor (Anypay) makes a payment request.
2) The wallet (Dash Electrum) constructs and signs the transaction.
3) The wallet sends the signed transaction directly to the payment processor for validation.
4) **If valid, the payment processor broadcasts the transaction -- not the wallet.**

This last step is the issue. The wallet should _not_ broadcast the payment. It should send the signed transaction to the payment processor to broadcast. _(I assume that Dash Electrum did broadcast the payment itself because otherwise I cannot explain how Anypay would have missed a payment that it broadcast itself, though perhaps there is another explanation.)_

One of the important reasons for this payment protocol is to **ensure that funds never leave a user's wallet without the payment processor acknowledging the payment**. Since a user reported that they paid an Anypay invoice but Anypay did not see it, I suspect that Dash Electrum may be broadcasting the payment itself rather than simply sending the signed transaction to the payment processor.

**It would greatly improve user experience for digital cash payments if your team could please check to see if Dash Electrum is indeed broadcasting the payments itself when handling a BIP70 payment request rather than simply sending the signed transaction to the payment processor.**

It is pretty important that the wallet _not_ broadcast the payment itself to reduce errors of the type described above. In that case, no Dash would leave the user's wallet, and the user could simply try again until the signed transaction is picked up by the payment processor and successfully broadcast.

_Thank you very much for your consideration of this matter! I am at your service to assist with any testing or questions._ 

Resources:
- [BIP70 Payment Protocol](https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki)
- [Anypay "Pay" Protocol](https://docs.anypayinc.com/pay-protocol/overview)

**Comment by zebra-lucky** [comment]
BIP70 is somewhat ambiguous related to broadcasting payment transaction.

In diagram and the description bitcoin client must broadcast:
> 3. Broadcast the transactions on the Bitcoin p2p network.

And then later:
> When the merchant's server receives the Payment message, it must determine whether or not the transactions satisfy conditions of payment. If and only if they do, it should broadcast the transaction(s) on the Bitcoin p2p network.

It is possible make code changes to not broadcast txs for Anypay,
but need more discussion to clarify BIP70 semantic.

**Comment by zebra-lucky** [comment]
Аfter reading BIP70 and dash core code found transaction
is broadcasted in core alongside with `Payment` message from BIP70:
https://github.com/dashpay/dash/blob/master/src/qt/walletmodel.cpp#L418

BIP70 also states client should broadcast.

It is still possible to change behaviour and not to broadcast tx for anypay payment request.
Support of Dash Testnet on payment server сould simplify task of testing changes.

BTW: BTC core removes BIP70 support:
https://github.com/bitcoin/bitcoin/commit/3548e4aac

**Comment by akhavr** [comment]
Should be fixed in #185 and released as a part of 4.0.9.2 release.

Reopen if your experience is different.
