### ISSUE TITLE
Trezor T not detected

### ISSUE THREAD

**Issue by mysliwiec-tech** [akhavr/electrum-dash#18]
Trezor T not detected by Electrum. 
Stuck on following screen:
![image](https://user-images.githubusercontent.com/7201544/37622814-0aeab9a0-2bc3-11e8-827f-c789c3b7f22d.png)
No errors in the logs, just it's not detected by the software.
OS: Windows 10

**Comment by dariuszmysliwiec** [comment]
Is there any way I can help with debugging it?

**Comment by akhavr** [comment]
Reopen if there's still an issue
