### ISSUE TITLE
Electrum Network/Цепочка блоков-Помощь на русском языке

### ISSUE THREAD

**Issue by btbw2020** [akhavr/electrum-dash#181]
В Electrum Network/Цепочка блоков-Помощь на русском языке приводится помощь на ошибочном языке (украинском).
https://i.imgur.com/agPtDTA.jpg

**Comment by akhavr** [comment]
Translations are done on Transifex.  The [translation of this line](https://www.transifex.com/dash/dash-electrum/translate/#ru/messagespot/160303455?q=translated%3Ayes+text%3A'local+copy') is fixed already and will be included in the package as soon as the russian translation would be completed.
