### ISSUE TITLE
SEED for Dash Electrum does not restore all balance and all transactions

### ISSUE THREAD

**Issue by luganskyi** [akhavr/electrum-dash#199]
Hello.

1. I have had Dash Electrum for almost 2 years. Constantly updated.

4.0.9.1

The fact is that the seed issued by the wallet I use is incorrect.

In the sense that if I restore the wallet using it again, it does not restore my entire balance and, as far as I can judge at a glance, not all transactions (perhaps I did not check the addresses).

I downloaded the latest Dash Electrum on Android, tried to restore it also through the SEED - similarly. There are not enough transactions, the balance is not complete.

I tried to open the wallet through a copy of the wallet file. All OK.

Honestly, for the first time I come across this - I was a little surprised :-) But it worries me. That SEED is somehow not SEED.

I can say that private send transactions were constantly coming to my addresses. In sufficient quantity.

2. Explain to me why the Dash Electrum SEED does not match the Dash Core SEED? Are they different things? Is that how it should be?

Are the wallet file from Core and Electrum also completely different unrelated entities?

-

As you can imagine, at the moment I can hope for a permanent backup of the exception of my private keys or wallet file. Otherwise, I lose access to all my funds, because your SEED is not completely correct. This worries me. And I would like to solve this as soon as possible.

-

Sorry for my English Google Translate :-)

If it is possible and convenient for you - tell me, I will communicate in Russian.

Thank you.

**Comment by akhavr** [comment]
Dash Core and Dash Electrum are different software, developed by different teams.

As far, as I understand you have two different wallets, one created using Dash Core, another one - created using Dash Electrum.  They have two different seeds because they are completely unrelated.  You should securely backup both of them.

Seed should restore all your private keys, but, by default, Dash Electrum doesn't scan very deeply.

Questions:
1. Are you trying to restore Dash Core wallet using your seed in Electrum?  Or did you have Dash Electrum wallet with many incoming transactions and now trying to restore it?
2. Did you mix using Dash Electrum or just receiving mixed funds?

Suggestion: try to increase [gap limit'](https://electrum.readthedocs.io/en/latest/faq.html#what-is-the-gap-limit) and see if it helps.  If not, please provide more information.

**Comment by luganskyi** [comment]
Hello.

Sorry for the long absence.

I have a Dash Electrum wallet with many incoming (and outgoing) transactions. I just grab SEED, trying to make a copy of the wallet, to check - that SEED will restore my entire balance :-)

Those. yes - I'm trying to restore Dash Electrum using its own SEED, which it gives me from the top menu Wallet - SEED. I have a wallet.

Initially, I thought that maybe I imported addresses manually sometime through importing private keys - that's why SEED simply doesn't "capture" them and when I restore a copy of the wallet - it doesn't restore the imported addresses.

But now I manually just compared all the addresses of both the original and the restored wallet.

It turned out that the addresses with the PS Keystore are simply not restored (the rest are restored normally).

I suspect this is something related to privatesend ... And then I'm already confused.

Have I personally used Private Send in my Dash Electrum? No never. Point - I rummaged through these settings, poked, tried to mix. Nothing got in the way. And I scored. Maybe it ruined everything ...

In fact, I only took the funds mixed by someone - yes. But he did not interfere. I used my wallet as usual. Wasted money. Accepted money.

I see that the number of transactions of the PS Keystore part of the addresses is greater than 0. Namely 2.

1. In general, I think after that everything became clear to you. Tell me what happened and how to solve it.

2. Just for curiosity. How to increase the gap limit? What am I doing wrong? I enter in the console

>>> changegaplimit (50)
Traceback (most recent call last):
  File "electrum_dash / commands.py", line 176, in _run
  File "concurrent / futures / _base.py", line 435, in result
  File "concurrent / futures / _base.py", line 384, in __get_result
  File "electrum_dash / commands.py", line 139, in func_wrapper
  File "electrum_dash / commands.py", line 795, in changegaplimit
Exception: WARNING: Are you SURE you want to change the gap limit?
It makes recovering your wallet from seed difficult!
Please do your research and make sure you understand the implications.
Typically only merchants and power users might want to do this.
To proceed, try again, with the --iknowwhatimdoing option.

Ok, I enter and get the same thing again.

>>> changegaplimit (50) --iknowwhatimdoing
Traceback (most recent call last):
  File "electrum_dash / commands.py", line 176, in _run
  File "concurrent / futures / _base.py", line 435, in result
  File "concurrent / futures / _base.py", line 384, in __get_result
  File "electrum_dash / commands.py", line 139, in func_wrapper
  File "electrum_dash / commands.py", line 795, in changegaplimit
Exception: WARNING: Are you SURE you want to change the gap limit?
It makes recovering your wallet from seed difficult!
Please do your research and make sure you understand the implications.
Typically only merchants and power users might want to do this.
To proceed, try again, with the --iknowwhatimdoing option.

3. Dash Electrum wallet file created on PC - can be transferred to phone (android, ios) - will the wallet work? Or different wallet files for different platforms?

4. SEED core and electrum - are they the same? Can you restore one from the other?

5. Are the core and electrum wallet files the same? Can they be used for recovery in both products (by moving to the correct folder)? Or are they completely different entities?

Thank.

**Comment by zebra-lucky** [comment]
1. On PrivateSend Keystore: it will be enabled and addresses will be generated
after enabling PrivateSend on wallet restored from seed. Possibly some coins is
denominated to PrivateSend denoms.

**Comment by zebra-lucky** [comment]
2. On gap limits. There is four if PrivateSend enabled: 
- Main addresses gap limit
- Change addresses gap limit
- PS keystore main addresses gap limit
- PS keystore change addresses gap limit

Gap limit is a count of addresses without transaction history generated by default
when wallet is created. Default is 20 for main and 10 for change. If there is no history
for more than gap limit addresses diapason then some coins can be not visible and
gap limit can be raised.

But from version 4.0.9.4 there is more convenient plugin `Scan Over Gap`, to scan
addresses sequentially and found lost balances. You can try it if enabling PrivateSend
is not enoug for you wallet.

**Comment by zebra-lucky** [comment]
3. On android wallet. You can transfer wallet by enterning seed.
Technically files are same, but this is not tested and some difference
in android app is presented and creation from seed is prefered.

**Comment by zebra-lucky** [comment]
> SEED core and electrum - are they the same? Can you restore one from the other?

Dash Core uses BIP39 mnemonic scheme. Dash Electrum uses own not compatible
with BIP39 shcheme. Dash Electrum can import wallets with BIP39 seed (from core),
but not reverse way.

**Comment by zebra-lucky** [comment]
5
> Are the core and electrum wallet files the same? Can they be used for recovery in both products (by moving to the correct folder)? Or are they completely different entities?

No, files are different, but you can restore wallet from BIP39 seed (from Dash Core) in Dash Electrum,
but only if Dash Core uses HD wallet option.

**Comment by akhavr** [comment]
@luganskyi did it work for you?

**Comment by akhavr** [comment]
Reopen if that didn't help.
