### ISSUE TITLE
Daemon subcommands not working (load_wallet, status, etc.)

### ISSUE THREAD

**Issue by CherryDT** [akhavr/electrum-dash#226]
After upgrading electrum-dash, our daemon code stopped working.

In particular, the command `electrum daemon load_wallet -w walletpath` stopped working with the error `electrum-dash: error: unrecognized arguments: load_wallet -w walletpath`, and none of the other commands like `stop`, `status` etc. work either.

I looked at the `--help` and I can't find how to load a wallet in any other way.

**Comment by akhavr** [comment]
You should first start it with `-d`:

```
./electrum-dash daemon -d
```

After the daemon is running, you can view your wallets:

```
./electrum-dash list_wallets
[]
```

load the wallet:

```
./electrum-dash load_wallet -w zzz
Password:
true
./electrum-dash list_wallets
[
    {
        "path": "/xxxxxx/zzz",
        "synchronized": true
    }
]
```

and stop the daemon:

```
./electrum-dash stop
Daemon stopped
```

If that won't work, please, reopen the issue and let us know your OS, electrum-dash version, and any other info that may be helpful.

**Comment by CherryDT** [comment]
Ah, OK, I missed that it's now a separate non-daemon command. I looked at `-w` and at the `daemon` command. Thanks for the pointer.

**Comment by CherryDT** [comment]
Hm but now the issue is that even though I loaded the wallet and `list_wallets` shows it, all my RPC commands fail with `Wallet not loaded`:

```
Apr 08 11:07:09 ip-172-31-20-79 electrum-dash-daemon-init.sh[27942]: E | daemon.CommandsServer | internal error while executing RPC
Apr 08 11:07:09 ip-172-31-20-79 electrum-dash-daemon-init.sh[27942]: Traceback (most recent call last):
Apr 08 11:07:09 ip-172-31-20-79 electrum-dash-daemon-init.sh[27942]:   File "/tmp/.mount_electrQJsimA/usr/lib/python3.7/site-packages/electrum_dash/daemon.py", line 209, in handle
Apr 08 11:07:09 ip-172-31-20-79 electrum-dash-daemon-init.sh[27942]:     response['result'] = await f(*params)
Apr 08 11:07:09 ip-172-31-20-79 electrum-dash-daemon-init.sh[27942]:   File "/tmp/.mount_electrQJsimA/usr/lib/python3.7/site-packages/electrum_dash/commands.py", line 132, in func_wrapper
Apr 08 11:07:09 ip-172-31-20-79 electrum-dash-daemon-init.sh[27942]:     raise Exception('wallet not loaded')
Apr 08 11:07:09 ip-172-31-20-79 electrum-dash-daemon-init.sh[27942]: Exception: wallet not loaded
```

It is electrum-dash version 4.0.9.3 on Ubuntu 18.04.4 LTS

**Comment by zebra-lucky** [comment]
Wallet with nondefault path should be passed as params:

```
"params": {"wallet": "filename"}
```

**Comment by akhavr** [comment]
@CherryDT if that doesn't solve your problem, please, reopen the issue.

**Comment by CherryDT** [comment]
Ah OK thank you, How can I set which wallet is the default then, so that the commands can work as before?

**Comment by zebra-lucky** [comment]
Default wallet is on '~/.electrum-dash/wallets/default_wallet` path

It can be loaded with `electrum-dash load_wallet` command (withouth `-w` option)

If you need RPC command on nondefault wallet, then set `"params": {"wallet": "filename"}`

**Comment by CherryDT** [comment]
I see... I'll solve this with a symlink then. Thank you.

**Comment by CherryDT** [comment]
I see... I have solved this with a symlink now. Thank you.

Interestingly, this works now in a good but unexpected way: `list_wallets` shows it with the real path (after resolving symlink), but it still works now without `wallet` parameter...! I think it would be cool if this could be achieved without symlink, maybe with an argument `--default` when loading the wallet...
