### ISSUE TITLE
Multisig: Transaction unrelated to your wallet error - precludes signing

### ISSUE THREAD

**Issue by pvesborg** [akhavr/electrum-dash#227]
Co-signer wallets cannot sign a multisig tx generated by the multisig wallet because upon import from text the "sign" botton is deactivated and the status is "Transaction unrelated to your wallet".

The error occurs for a 4-of-5 wallet. We haven't tested other setups.

**Comment by zebra-lucky** [comment]
Tested 4of5 multisig setup. Seems it working.

Can you check, please, you wallets setup?
Possibly configuration is something different (3of5 for example).
Wallet info can be get from main menu "Wallet -> Information"

Another check if addresses is same on "Addresses" tab.
Can be envabled with from main menu "View -> Show Addresses"

**Comment by pvesborg** [comment]
Well that's strange. We tested both an old multisig wallet which has been
broken ever since version 4.0.4 (but which works fine in version 3.3.8.7).
The problem persists on both Mac, Windows and Linux.

For the new version 4.0.9.4 we easily reproduced the problem with a brand
new wallet.
Procedure:
1) Make a 4-of-5 multisig wallet (have seed) and using 4 master-pubkeys
from 4 other (normal) wallets. => OK
2) Make a multisig transaction, using the multisig wallet obviously, and
thus get signature 1 (out of the 4). => OK
3) Upon importing the partially signed tx into any of the other 4 wallets
we get the "tx unrelated to your wallet" message and an inability to add a
signature.

Strange. But so far, we must still stick to 3.3.8.7.

**Comment by zebra-lucky** [comment]
I'll try to reproduce the problem with described setup.

**Comment by pvesborg** [comment]
Great!

Here's some screenshots in case it helps finding the problem:




Multisig wallet:



And number two keystore in above on the multisig wallet (Keystore 1 is
selected):



Below is the keystore 2 wallet information:



Adresses within Multisig:





This is the transaction signed by the multisig wallet:



Export is:

cHNidP8BAHUCAAAAASt651f68fx80G59cdtnU29Q3FxKzVQJIdYsB3NPRnONAAAAAAD+////AmYVAAAAAAAAF6kU4QojhNdwOI3WGw63gER9kzU4tAaHUEHmAAAAAAAZdqkUYboPQ+E8HN9byB22vEb9rxYvA4yIrK0qFgAAAQD9KRgCAAAADH7b+5HGadIs3deboTT8s00vbEe2jHDvPtOdyOj1OkchAAAAAP3SAQBIMEUCIQCweTPL1pF86rRfzPYoS4fNhMLtVGHgA7UvP51T5XT0FAIgNLOSCeHccTRvWOTFsU5ukyOYYXGa/abSzB/B/RLhjOYBRzBEAiAeVgtCbyxBfGcTNk/S5I5X7rgAfxw3KDWcKhKDtZXdrgIgIzXiipiAGT0PBP67cTSKqe4GPCLeznFMXR9YPcw2BIgBRzBEAiAx0E5Y1Pg9IeO95qnIg5lSX/pBE7NZlz/WvmplcVr3DAIgX7EcMEqSwpw8OPnlQe0w7qKvdB3Mm47VLuEGDucxJfYBSDBFAiEAqTXiUoNdALkXOD5/TtSJicvomgJ3hVux1tsO+vbM87ECIG4CuqeQigMEOh0pRqHW4MhehyQ3/eJW5Wx6Em1Ki5qWAUytVCECBV4xcsWzksgyq8m/eZNvmjox3LYbPS7Hy+l7ABKIpeohAq5ah6qXe9gAMLAzhcuxk1irYsj4pvFPm9xmNFmgwKayIQNqgDAgfIPObL0tEVA6ZnPAoOTgv+PEBwrDegdKWxUExSEDxX9vA51mc/vbaiHTrORs8lnN0IG9PIvrsOPWqCtcpXAhA/A5gduEigLLLQuVL89CYlx9dWpZ+pTWbkld5C1/ohMQVa7+////e7LjUKUh6jFY4bORGETgLvASSIatNJAhv0IL9ucCqyMAAAAA/dEBAEgwRQIhAM7t3LyfeNgOcB3T6QwKfWrtlD9yNZrl0oNyI7hZx+CRAiAGiR4/d3dxN/ebqewCigOHoI+2kTeEvThbPD8ZPC5TtAFHMEQCIGUhKph9RsFJcxZcz91k2bYJNYaE7+CoOqXUUXwXAlCxAiAkHROKqBCsUJXD+aVvWHjnNQSUQpDYrq2gLlUIc2QOyQFHMEQCIC1QzxZCDlyb6YwquKqWL9dsUSZuMBXGXthvOeTgFHNxAiAVa0tlVeFgUrzfiKepm2HEXP4evoV90M4IsMFzxQuuDwFHMEQCIDXwQxmZDbrCr7iorL8lNvWUX4G9lHfLxn8Ga/WtRvlfAiA9+Xy62eRCjeV5hkLzlfz8nq8zi1DZrlNl1+tsc0VIawFMrVQhAgVeMXLFs5LIMqvJv3mTb5o6Mdy2Gz0ux8vpewASiKXqIQKuWoeql3vYADCwM4XLsZNYq2LI+KbxT5vcZjRZoMCmsiEDaoAwIHyDzmy9LRFQOmZzwKDk4L/jxAcKw3oHSlsVBMUhA8V/bwOdZnP722oh06zkbPJZzdCBvTyL67Dj1qgrXKVwIQPwOYHbhIoCyy0LlS/PQmJcfXVqWfqU1m5JXeQtf6ITEFWu/v///5EC8a5hKfb+06Sp8+FYxzyzO8unrSiJBJc1Kcx3OsAjAAAAAP3TAQBHMEQCIBUWiFV6DdCDtul7X9+DrinV8+0/HMTmXa3pe2NQc+jQAiB+VbKItpe3gGoy+HxSsjtkaoKFg5Xoag0klxFXicT+bAFIMEUCIQDaExA7WDXTTJsn5mTLA9+qJoN4dueVBT70SanXl6Vu7wIgMa+h2E7X9d/gtIuyed32BRz0f9qZGID9LddNTE4O498BSDBFAiEAverMqMyIH74Vvf257YE4AxjcI6fsWCZVU/LeG50wv5YCIBU/HV4Gsxg9aGTU1LUBLqrsBNqq4A+LdgtirmfNUyGJAUgwRQIhAImSlQW1RMbkqKX3RwWkxb8/BozjyxNAWi+pVJmgL5iMAiB6rR4qb7R7ffuexgR13yxKDgW5mqqpn8Eip8fLD5tghgFMrVQhAgVeMXLFs5LIMqvJv3mTb5o6Mdy2Gz0ux8vpewASiKXqIQKuWoeql3vYADCwM4XLsZNYq2LI+KbxT5vcZjRZoMCmsiEDaoAwIHyDzmy9LRFQOmZzwKDk4L/jxAcKw3oHSlsVBMUhA8V/bwOdZnP722oh06zkbPJZzdCBvTyL67Dj1qgrXKVwIQPwOYHbhIoCyy0LlS/PQmJcfXVqWfqU1m5JXeQtf6ITEFWu/v///0cPK0wOJYtoxr2wqKpj1EYezLBibVzojfIHh6yVExBHAAAAAP3RAQBHMEQCIEdYh3DiCFxOkfMUPeCiAs181C41yn649o+C9OpOv4X6AiA726w29hAob5sFY4BSSk1oCT0ifcv6AZV2I+D+79OkJwFIMEUCIQCOVMi5AGdE4rqaQXSbeeLkg7ZwQrIDaia0cmaSjV7VoQIgcD17zxpaZnNygE7M/kbkBa5LV0nxK238V6RYp7RXrjwBRzBEAiAfWLkgv4mQZK31Z1Oo375WRjqmSIsYVZdhhVfsp8M+aQIgThCJfblBdObdkaFCb1+hHHRmkmkEsRTqSNFhQdsgJ9ABRzBEAiALY0oxVUvrlRbLYkIeG/tW+b29AplzeBedwpHyLAwUmAIgQKOMO9s6T5z244Gl9oP/JO5tNzhE41nDg4eO1jSAjMABTK1UIQIFXjFyxbOSyDKryb95k2+aOjHcths9LsfL6XsAEoil6iECrlqHqpd72AAwsDOFy7GTWKtiyPim8U+b3GY0WaDAprIhA2qAMCB8g85svS0RUDpmc8Cg5OC/48QHCsN6B0pbFQTFIQPFf28DnWZz+9tqIdOs5GzyWc3Qgb08i+uw49aoK1ylcCED8DmB24SKAsstC5Uvz0JiXH11aln6lNZuSV3kLX+iExBVrv7///+e5BkOlvUP+lb1/JTxTekaOQxZ7ZQurG73XzlEnNU4SwAAAAD90gEARzBEAiB2Svht+ISR/tYlpk3u+p9typawOSVCE/KDXVxi6WrztAIgN+M8UfdDj87ZmY/qgvXsdJMJXelOpc8To4YrJ+j6RrEBRzBEAiAY5tmFbwcu99dy5b6NTytxddzyW0fbzhr6+UtAFg224QIgayvAQx63ukUaOCiEd06mGMfxXYYQh8WkJOL9RY0z7NoBSDBFAiEAtV/xGE5IYrVw5dx16HAGqE11tv9Hap1S9ugQdFs95XUCID5ufFfBtUZyuXOZ6kHeEYQSxB/dcC4+D0qoMBIgDmBeAUgwRQIhAMGcOKCGd3iQr8AWd11+YrbPbG0bOSfgp0Mnnmj6Ot0uAiBjQZCZI+OO5pL0qgTprLbjoS9CL5C2NXK8Kk/2lRrYTgFMrVQhAgVeMXLFs5LIMqvJv3mTb5o6Mdy2Gz0ux8vpewASiKXqIQKuWoeql3vYADCwM4XLsZNYq2LI+KbxT5vcZjRZoMCmsiEDaoAwIHyDzmy9LRFQOmZzwKDk4L/jxAcKw3oHSlsVBMUhA8V/bwOdZnP722oh06zkbPJZzdCBvTyL67Dj1qgrXKVwIQPwOYHbhIoCyy0LlS/PQmJcfXVqWfqU1m5JXeQtf6ITEFWu/v///zhW4cIPE4k1jMLZjW3uX3josJktYZxjtrTw3XBXhxtOAAAAAP3TAQBIMEUCIQCsXbP/5Mw5IU9A6uINBN/BP2FEeeYNTqhO6v15SJ5qNgIgcntvys448Cs73TaSAaI9ktqy2L/YnxQ2BTHWS03cGccBSDBFAiEAqd0P5XQNwnoYQFxV82ULasNIXRyLlqVu3NC4rN2xguMCIFG8zMfQ5qy67HlXwBugO7ct8SBPwQXnWdb2sZlqgax2AUcwRAIgCLl6P6LOc1sIYSXUQPrrS1P+DGngDknaRS3hT7gUpgECIDtbDFlIAxPiXFXepfJntN9Ly+bRHPJJCzrcYurEfsT2AUgwRQIhAMEp/NZthSn2axZ3unxoCvJhEJL4oyVkOCBgwcydlWPPAiB2Z+VaIBUoS57RByWtUCwnR58cGgllc6Ry2M/EOOrhiwFMrVQhAgVeMXLFs5LIMqvJv3mTb5o6Mdy2Gz0ux8vpewASiKXqIQKuWoeql3vYADCwM4XLsZNYq2LI+KbxT5vcZjRZoMCmsiEDaoAwIHyDzmy9LRFQOmZzwKDk4L/jxAcKw3oHSlsVBMUhA8V/bwOdZnP722oh06zkbPJZzdCBvTyL67Dj1qgrXKVwIQPwOYHbhIoCyy0LlS/PQmJcfXVqWfqU1m5JXeQtf6ITEFWu/v///6LRJKGl0IpHB1Wx1H67UoCRMs7ThAl6ExftPoSx1RhlAAAAAP3SAQBIMEUCIQDWF09OjxFLhq9NEtWHgKqXvbaH3JoSR9j6Q6OcDXzTkAIgFeUmIX5ojnV37JYoZlLZqvNd0EGtmkmuURV05gIJbsUBSDBFAiEA3LtVwe3WP6cQgK7WNO3PTKq0Nh+Aq6dd3hmyzGR5HgMCIG4AYAFkbGbXPG/AB01DJcrXpulI0VMkpgeRNiBC50ubAUcwRAIgY9+FpkkvBh6n1LzE8ph8o5YWuqPlmSgsrELHut8o+nUCIG04ziGAitEYnVOBVd1U++6vlGtx1VTMxFDeMvbSohpLAUcwRAIgDsDxtZ49UbcH2LwLE6tffySuGSgJlxYdFZulP+xA4IkCICYi3tBQkywp8BilclWO27Oq3oLlIpigjnCy/uWCoCk3AUytVCECBV4xcsWzksgyq8m/eZNvmjox3LYbPS7Hy+l7ABKIpeohAq5ah6qXe9gAMLAzhcuxk1irYsj4pvFPm9xmNFmgwKayIQNqgDAgfIPObL0tEVA6ZnPAoOTgv+PEBwrDegdKWxUExSEDxX9vA51mc/vbaiHTrORs8lnN0IG9PIvrsOPWqCtcpXAhA/A5gduEigLLLQuVL89CYlx9dWpZ+pTWbkld5C1/ohMQVa7+////6HB//xI5BIcp6APSmsqw87ltd/qdnP2GbEiSSwq2sosAAAAA/dMBAEcwRAIgDWsmTQs7Hgc896LgjWPeuKn0MILgShSjWBYOGpKaEBoCIA0MMKn++01LLOX9DF+PWpH+5c/s1sF9MVSFPvyplwYJAUgwRQIhAPDSX7btCskrbg9djB7i2vlyTK8/3xcxdf3bBI7J9FPnAiA/bgH1DXYd5U95gX8kA5TewROeC7l3+3WdeCzHTReaAAFIMEUCIQCIc6bT3/10aFsmv8Zu4FHH2GEePpFivoOsMw6ETngPvAIgGJi3+lZMPG3trd+M434lf9Ei2+ig5etZm2WlSGnLBLQBSDBFAiEAuybDLyCpyo/IklOzEPjfhJPsed/bw33ccBxDHN3HNckCIF7OIoqC+oU36DGNuVRTRcwNJnHB+8RoP5ucTG+j5fMFAUytVCECBV4xcsWzksgyq8m/eZNvmjox3LYbPS7Hy+l7ABKIpeohAq5ah6qXe9gAMLAzhcuxk1irYsj4pvFPm9xmNFmgwKayIQNqgDAgfIPObL0tEVA6ZnPAoOTgv+PEBwrDegdKWxUExSEDxX9vA51mc/vbaiHTrORs8lnN0IG9PIvrsOPWqCtcpXAhA/A5gduEigLLLQuVL89CYlx9dWpZ+pTWbkld5C1/ohMQVa7+////imZW0wqx5vQDuWwaN4Noj3WYsbX9LPRkRDAndAQ43MgAAAAA/dEBAEcwRAIgSBESyUMdiX76oEXWadZADZ+w9S6LNXe6d6jVTrb/jyMCID9wFrCSMnGIhmAigrYpV+PeO8CJ2csTsFYKUfFsw/1+AUcwRAIgJHZ5NtkGAzfTM8n5h4PLHwuRYqbCjiBvkemyH9CZfXYCID8Q0GKOkaOUZYq6s6k2tIG09IX7riYOUdJp+0pNmxMHAUgwRQIhAIQjYk8KmQRp+hy4tduRoXtchQ4ivAoxf/xWRu8e89w1AiApO4CcaYFMHxj4U3+GmgVsx7tQv3WOcwGc3k5CBekZvwFHMEQCIEXPRSBxdBXk90Qi5bmz2V2LfOHJu7lj0e9zxqV8BhPAAiBO3xsIaFkMHeSC1PKz3DPLyMPEZ9ht38luGME7sdTd/wFMrVQhAgVeMXLFs5LIMqvJv3mTb5o6Mdy2Gz0ux8vpewASiKXqIQKuWoeql3vYADCwM4XLsZNYq2LI+KbxT5vcZjRZoMCmsiEDaoAwIHyDzmy9LRFQOmZzwKDk4L/jxAcKw3oHSlsVBMUhA8V/bwOdZnP722oh06zkbPJZzdCBvTyL67Dj1qgrXKVwIQPwOYHbhIoCyy0LlS/PQmJcfXVqWfqU1m5JXeQtf6ITEFWu/v///w53gbPhA1yeeUYPW5MVoU3rSZr6k9o4tP+CAzD4TkThAAAAAP3RAQBIMEUCIQChl4Ym8SIx4EI2hR5h0zd2AEUpRM/IPDXqbpIldOXuiAIgXSSgAVuGzjoFJ+ctIsdeOxZhT3vPOxCo+I1hAK88uhYBRzBEAiBeh8wP5VnhOncXsnfdWRV94cZSYKmtRuJEsMoZC86+/gIgfyXdbOOtxUMPDU26HH+1uLyReKx/MDZNyu6lIbN9ypUBRzBEAiA8XtgsSKpBaadQnhbf7pRd+kY4rx44Cgfp+Jdw7U1+YwIgIF3AJFU9f9Z6T3jYBl4s4KV2yplFXkKH3HatSqj7iJ4BRzBEAiAOt1MbWQdKHVohi16MkZcOay96zpwV74mX81jAXNQSQQIgL0y/hdpbYCvdorCs3r3KYjar+GdBYZsoZFU7F4S7kwEBTK1UIQIFXjFyxbOSyDKryb95k2+aOjHcths9LsfL6XsAEoil6iECrlqHqpd72AAwsDOFy7GTWKtiyPim8U+b3GY0WaDAprIhA2qAMCB8g85svS0RUDpmc8Cg5OC/48QHCsN6B0pbFQTFIQPFf28DnWZz+9tqIdOs5GzyWc3Qgb08i+uw49aoK1ylcCED8DmB24SKAsstC5Uvz0JiXH11aln6lNZuSV3kLX+iExBVrv7///8eGkBQetuHDszF88QaBMXOTyOi3nTYyC/xnM0V88Ew+wEAAAD90gEARzBEAiAUUPhaTLLgFriMNP70t9D1KFvoiGAA0x2/cmq23D0pFQIgZxXOu4vG9GayL1ySUHpEtV1cAyF5QFYVTEsQ369fGisBRzBEAiATEMztBNgZDCnVJpRuPrPK6GfPGI0kLv7Yo5RwrI7QeQIgfkyzbT+NG8ef4HUMFeniDWb1WuupxkvWVUew3Puv2NoBSDBFAiEA/CGabQCR9AbPbV2oeGN3nOg0PFxZORopUg9nxBfKk7wCIEl4h3g2l+Rgwel6BKNgAE3yyqLJFtJ2mPm0nMlITf/wAUgwRQIhAOYvmida76Yh4gbjRjrWkovw6Yl56X2TSpiQ3JYuGpIQAiBV398D1sCTw1Z/D/z+cQZDInOfa8AoOEpn/vr8NnGl4gFMrVQhAgVeMXLFs5LIMqvJv3mTb5o6Mdy2Gz0ux8vpewASiKXqIQKuWoeql3vYADCwM4XLsZNYq2LI+KbxT5vcZjRZoMCmsiEDaoAwIHyDzmy9LRFQOmZzwKDk4L/jxAcKw3oHSlsVBMUhA8V/bwOdZnP722oh06zkbPJZzdCBvTyL67Dj1qgrXKVwIQPwOYHbhIoCyy0LlS/PQmJcfXVqWfqU1m5JXeQtf6ITEFWu/v///zjNhnK5EQ4NpS8B0NUUxjwoq7/r5m6M4/0zCemr/Ov+AAAAAP3UAQBIMEUCIQCYC3FOwwyeNhYd6i/hW1MCaMBvGQ0PCt4GrOZMx3Z8QgIgb5r7e3j/pk2IVU8dHyR0AR5hRJAJBn3jteXcNVcO42EBSDBFAiEA3zBHKiLMjYxjxjDLjysncYccfPTRWbmrWrMIzhlcH5YCIC/ApQ/xJEmkPCE7tkUy7RTTcmvLvKO8I8iULMVGc0rwAUgwRQIhAJ7pRbpioMtpU46Egy+iS7JQl1kNx3nRfDLYTvtCOkXdAiAyvVacmr/7mqUZbxkHhtRdpQMV2uAYRImrpDRA0OemzgFIMEUCIQCx7v1O0GrtYbzooS1WTdBUpA9bzvAFKmvyAoWofWEPgAIgBdaLCxfJ5z99rKbR3bKDf0atQFFfD8bbBWai0ECmi18BTK1UIQIFXjFyxbOSyDKryb95k2+aOjHcths9LsfL6XsAEoil6iECrlqHqpd72AAwsDOFy7GTWKtiyPim8U+b3GY0WaDAprIhA2qAMCB8g85svS0RUDpmc8Cg5OC/48QHCsN6B0pbFQTFIQPFf28DnWZz+9tqIdOs5GzyWc3Qgb08i+uw49aoK1ylcCED8DmB24SKAsstC5Uvz0JiXH11aln6lNZuSV3kLX+iExBVrv7///8CAVnmAAAAAAAXqRThCiOE13A4jdYbDreARH2TNTi0BocAA5olGgAAABl2qRS3ySuo48ZSXeNWFGOGQXP/JzmyGoisN98VACICAq5ah6qXe9gAMLAzhcuxk1irYsj4pvFPm9xmNFmgwKayRzBEAiBNEMHCqDJvtvzg+2dCPnr0HHgUPDGjFA2VT12CWnNoegIgf0zc3bAt+26jOVFNUEM38cvwA8JtGOl3lUJhQLMfozABAQStVCECBV4xcsWzksgyq8m/eZNvmjox3LYbPS7Hy+l7ABKIpeohAq5ah6qXe9gAMLAzhcuxk1irYsj4pvFPm9xmNFmgwKayIQNqgDAgfIPObL0tEVA6ZnPAoOTgv+PEBwrDegdKWxUExSEDxX9vA51mc/vbaiHTrORs8lnN0IG9PIvrsOPWqCtcpXAhA/A5gduEigLLLQuVL89CYlx9dWpZ+pTWbkld5C1/ohMQVa4iBgIFXjFyxbOSyDKryb95k2+aOjHcths9LsfL6XsAEoil6gxSryDPAAAAAAAAAAAiBgKuWoeql3vYADCwM4XLsZNYq2LI+KbxT5vcZjRZoMCmsgyHWzAFAAAAAAAAAAAiBgNqgDAgfIPObL0tEVA6ZnPAoOTgv+PEBwrDegdKWxUExQzKhvW1AAAAAAAAAAAiBgPFf28DnWZz+9tqIdOs5GzyWc3Qgb08i+uw49aoK1ylcAxJljrIAAAAAAAAAAAiBgPwOYHbhIoCyy0LlS/PQmJcfXVqWfqU1m5JXeQtf6ITEAymtT/uAAAAAAAAAAAAAQCtVCECBV4xcsWzksgyq8m/eZNvmjox3LYbPS7Hy+l7ABKIpeohAq5ah6qXe9gAMLAzhcuxk1irYsj4pvFPm9xmNFmgwKayIQNqgDAgfIPObL0tEVA6ZnPAoOTgv+PEBwrDegdKWxUExSEDxX9vA51mc/vbaiHTrORs8lnN0IG9PIvrsOPWqCtcpXAhA/A5gduEigLLLQuVL89CYlx9dWpZ+pTWbkld5C1/ohMQVa4iAgIFXjFyxbOSyDKryb95k2+aOjHcths9LsfL6XsAEoil6gxSryDPAAAAAAAAAAAiAgKuWoeql3vYADCwM4XLsZNYq2LI+KbxT5vcZjRZoMCmsgyHWzAFAAAAAAAAAAAiAgNqgDAgfIPObL0tEVA6ZnPAoOTgv+PEBwrDegdKWxUExQzKhvW1AAAAAAAAAAAiAgPFf28DnWZz+9tqIdOs5GzyWc3Qgb08i+uw49aoK1ylcAxJljrIAAAAAAAAAAAiAgPwOYHbhIoCyy0LlS/PQmJcfXVqWfqU1m5JXeQtf6ITEAymtT/uAAAAAAAAAAAAAA==



Upon loading the transaction in approver 1 wallet ( >Tools>Load
transaction>From text ) I get this and cannot continue:









 --------- Forwarded message ---------

From: *zebra-lucky* ***@***.***>
Date: Fri, Apr 9, 2021 at 7:54 PM
Subject: Re: [akhavr/electrum-dash] Multisig: Transaction unrelated to your
wallet error - precludes signing (#227)
To: akhavr/electrum-dash ***@***.***>
Cc: pvesborg ***@***.***>, Author ***@***.***>



Tested 4of5 multisig setup. Seems it working.

Can you check, please, you wallets setup?
Possibly configuration is something different (3of5 for example).
Wallet info can be get from main menu "Wallet -> Information"

Another check if addresses is same on "Addresses" tab.
Can be envabled with from main menu "View -> Show Addresses"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akhavr/electrum-dash/issues/227#issuecomment-816853538>,
or unsubscribe

**Comment by zebra-lucky** [comment]
I've tested described setup on 2of2 multisig wallets (1of2, 2of2)
and standard wallets with first seed and second seed from multisig.

Seems it really worked on 3.3.8.7 (upstream 3.3.8 version).

I've found related issue in upstream code:
https://github.com/spesmilo/electrum/issues/6579

Citation from there:
> So you have two wallet files, a 2of2 multisig that presumably has private keys for one cosigner, and a standard single-signer wallet that has private keys for the other keystore. This setup was never intended to work, it just used to work due to a bug.

And related issue where this bug was reported:
https://github.com/spesmilo/electrum/issues/5948

**Comment by zebra-lucky** [comment]
If I rightly understand you have same problem on 4.х code branch,
where bug described in https://github.com/spesmilo/electrum/issues/5948 was fixed.

**Comment by pvesborg** [comment]
Yes,  it seems like it's the same problem. certainly related.

But if I understand the discussion in the link you sent correctly,  it
seems that the root cause is that I'm somehow using multisig incorrectly?
Again - our procedure is to
1) create 4 *standard* wallets.
2) create 1 (4of5) multisig wallet importing the xpubs from the 4 standard
wallets.


If that's not the right way to do it I'd like to know what the correct
procedure is.  The documentation is either outdated or inadequate.

cheers,  and thanks for looking into this!

**Comment by zebra-lucky** [comment]
> Again - our procedure is to
> 1) create 4 *standard* wallets.
> 2) create 1 (4of5) multisig wallet importing the xpubs from the 4 standard
wallets.

Not sure about 5-th xpub/seed for your setup,
but for 4of5 procedure is something like:

Create 5 wallets (type multisig 4of5):

- In first entered first seed and 4 xpubs from 2, 3, 4, 5
- In second entered second seed and xpubs from 1, 3, 4, 5
- In third entered third seed and xpubs from 1, 2, 4, 5
- In fourth entered fourth seed and xpubs from 1, 2, 3, 5
- In fifth entered fifth seed and xpubs from 1, 2, 3, 4

In that setup all wallets have same addresses set and show
history of transactions on these addresses. To sign transaction
any four wallets is enough.

It is also possible to create watch only multisig, where only xpubs 1, 2, 3, 4, 5
is entered in multisig 4of5 wallet setup.

**Comment by zebra-lucky** [comment]
P.S.: In 4.0.9.4 version there is new possibility for multisig setup,
where you can save wallet before all xpubs is entered.
It is simplify createion of multisig wallets.

For expamle when you create `walet1_4of5`, generate seed
and confirm seed and there is no other xpubs to enter, there
is possibility to save unfinised wallet setup, to continue enter
xpubs later, or look or copy xpub for other wallets setup.

**Comment by akhavr** [comment]
@pvesborg   did you managed to change your setup so tx signing works?

**Comment by pvesborg** [comment]
Yes,  if we make 5 multisig wallets it seems to work. Thanks a lot for your
help!

**Comment by akhavr** [comment]
Closing
