### ISSUE TITLE
Hardware wallet based multisig MN wizard warning

### ISSUE THREAD

**Issue by thephez** [akhavr/electrum-dash#232]
I ran into this in v4.0.9.4 when investigating the possibility of setting up a testnet masternode from a 2 of 2 multisig wallet where both cosigners were hardware wallets. It indicates that a MN could be registered by ignoring the message, but not fully managed as ProUpRegTxs could not be done. Is this something that should be possible or will be possible in a future release?

Looks like the error message is coming from : https://github.com/akhavr/electrum-dash/blob/master/electrum_dash/gui/qt/protx_wizards.py#L1595-L1600

Also possibly relevant. I used a non-default derivation path since `m/45'/0'` is the default for both testnet and mainnet across multiple coins ([BIP45](https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki) doesn't include the concepts of multiple accounts/coins) so it really probably shouldn't be used.

![image](https://user-images.githubusercontent.com/8145677/114400242-c42eab00-9b6f-11eb-93e0-d7185dd30c8b.png)

**Comment by zebra-lucky** [comment]
This warning is errornous, but on P2SH wallet must be similar warning.

ProUpRegTx requires `payloadSig`:
> Signature of the hash of the ProTx fields. Signed by the Owner.

HW wallets can only sign tx and message, as far as I know, but not hash.
So `sign_digest` is implemented in software keystores in Dash Electrum,
adn for hardware keystore for P2PKH standard wallet with hardware keystore
this warning notice on impossibility to sign ProUpRegTx.

For multisig P2SH wallets Owner address must be of type P2PKH, and unknown
to wallet, so must be same warning if other P2PKH wallet have hardware keystore,
which is unknown programmatically.

**Comment by zebra-lucky** [comment]
I'll add commetn, when this bug will be fixed
(only message will change on P2SH wallets).

**Comment by akhavr** [comment]
New warning message will be

> Warning: sign_digest is not implemented in hardware wallet keystores. If address you set as Owner address belongs to hardware wallet it is impossible to sign a `ProUpRegTx`.

or
> Warning: `sign_digest` not implemented in hardware wallet keystores. You cannot use this wallet to sign a `ProUpRegTx.` 
if current wallet is hardware.

This will be followed up with

> You can still register a masternode, but in the future it will be impossible to change voting/payout addresses or ' the operator public BLS key

Closing.
