### ISSUE TITLE
Error creating new denoms tx: Insufficient funds

### ISSUE THREAD

**Issue by PanosChtz** [akhavr/electrum-dash#236]
I have about 0.065 Dash in my wallet and want do mix them, but I get an insufficient funds error.
I don't believe this should be happening because I can mix these coins using the exact same amount.

Log follows
```
04/16/2021 02:21:17 PM Created new denoms tx: cbdad44c3991a541edaf6ccba7a939c1f860a9815935a75dc594bf89c51c1b13, workflow: 67af8996
04/16/2021 02:21:17 PM Error creating new denoms tx: Insufficient funds, workflow: 67af8996
04/16/2021 02:21:17 PM ps_collateral outpoint cbdad44c3991a541edaf6ccba7a939c1f860a9815935a75dc594bf89c51c1b13:0 is not confirmed
04/16/2021 02:21:17 PM Cleaned up new denoms tx: cbdad44c3991a541edaf6ccba7a939c1f860a9815935a75dc594bf89c51c1b13, workflow: 67af8996
04/16/2021 02:21:17 PM Cleaned up new denoms workflow: 67af8996
04/16/2021 02:21:52 PM Started up new denoms workflow: 81a1ed43
04/16/2021 02:21:52 PM _add_tx_ps_data: matched removed tx cbdad44c3991a541edaf6ccba7a939c1f860a9815935a75dc594bf89c51c1b13
04/16/2021 02:21:52 PM Created new denoms tx: cbdad44c3991a541edaf6ccba7a939c1f860a9815935a75dc594bf89c51c1b13, workflow: 81a1ed43
04/16/2021 02:21:52 PM Error creating new denoms tx: Insufficient funds, workflow: 81a1ed43
04/16/2021 02:21:52 PM Cleaned up new denoms tx: cbdad44c3991a541edaf6ccba7a939c1f860a9815935a75dc594bf89c51c1b13, workflow: 81a1ed43
04/16/2021 02:21:52 PM Cleaned up new denoms workflow: 81a1ed43

```

**Comment by akhavr** [comment]
How many rounds of mixing are you performing?  Remember, that part of the funds is reserved for the collateral.

Investigating it..

**Comment by akhavr** [comment]
Also, if you would share the sizes of your UTXO's, that also would help debugging.

Thanks

**Comment by PanosChtz** [comment]
The attempt above was for two rounds. I sent the funds to another address and sent them back to my wallet. Then the mixing happened normally.
But then I wanted to do mix for 4 rounds. The mixing stalled in the middle with the same insufficient funds error. Here's the error log
https://pastebin.com/AjEbzY16
Please let me know if you need anything else that helps (e.g. how do I find the UTXO sizes?)

**Comment by akhavr** [comment]
> how do I find the UTXO sizes?

Go to View menu and make sure that Coins tab is shown (`Show Coins`).  Then you can go to Coins tab and see what unspent outputs you do have.

**Comment by akhavr** [comment]
Also, have you changed anything in PS dialog?   We've recently introduced more flexibility in creating denominations.  Is it set to "Use default denoms count" or "Use absolute denoms count"?

**Comment by PanosChtz** [comment]
Ok I will report back if this occurs again.


> 
> 
> Also, have you changed anything in PS dialog? We've recently introduced more flexibility in creating denominations. Is it set to "Use default denoms count" or "Use absolute denoms count"?

I didn't change that option, I see it is set as "Use default denoms count". Should I try the other one? What does it do?

**Comment by akhavr** [comment]
> I didn't change that option, I see it is set as "Use default denoms count". 

Ok

> Should I try the other one? What does it do?

No, don't change it unless you know what are you doing.

It allows you to set up the size and number of denominations to be mixed later.  

For example, if your payments are usually small, it's better to create a lot of small 0.01 Dash denominations.  OTOH, if you shuffle sizeable amounts, it's better to mix 10Dash outputs.
