### ISSUE TITLE
macOS run blocks (unidentified developer)

### ISSUE THREAD

**Issue by zebra-lucky** [akhavr/electrum-dash#245]
Possibly need to clarify in docs how to make first run:

Via preferences -> Security & Privacy

![Screenshot from 2021-05-10 16-25-11](https://user-images.githubusercontent.com/992125/117673114-256b8d80-b1b3-11eb-9939-54d0daca6505.png)

**Comment by zebra-lucky** [comment]
Same for Win10

**Comment by zebra-lucky** [comment]
Found this already described in docs:

https://github.com/akhavr/electrum-dash/blob/master/docs/os-specific.md

possibly issue can be closed

**Comment by akhavr** [comment]
Ok
