### ISSUE TITLE
Is this the official Dash Electrum repo?

### ISSUE THREAD

**Issue by dev-bre** [akhavr/electrum-dash#249]
I am really confused about which one is the official repo for Dash Electrum. On the DashPay GitHub account, referenced on their website, the electrum-dash and many other repos are all marked as Archived. 

Then I found this repo mentioned in the Dash Forum and mentioned as official for Electrum.

That's all really confusing, and am sure many others share the same concern. 

Why not using the official DashPay GitHub account instead??

**Comment by akhavr** [comment]
Because DashPay is a github organization for Dash Core Group.

Dash Electrum is developed here, independently, with financial support from Dash Treasury.
