### ISSUE TITLE
mixer not working anymore

### ISSUE THREAD

**Issue by anondashuser** [akhavr/electrum-dash#267]
Hello, I have an electrum wallet but recently it stopped mixing coins. I am using Dash Electrum 4.0.9.4 on macOS Catalina.

If I watch the log I find:
06/10/21 ... Finding untracked PrivateSend transactions
06/10/21 ... No untracked PrivateSend transactions found
06/10/21 ... awaiting wallet sync
06/10/21 ... wallet synced
06/10/21 ... Finding untracked PrivateSend transactions
06/10/21 ... Found PrivateSend fdb...
06/10/21 ... Finding untracked PrivateSend transactions
06/10/21 ... No untracked PrivateSend transactions found
06/10/21 ... Finding untracked PrivateSend transactions
06/10/21 ... No untracked PrivateSend transactions found
06/10/21 ... Starting PrivateSend Mixing
06/10/21 ... Started PrivateSend Mixing

And then nothing else happens.

Thanks

**Comment by akhavr** [comment]
We're working now to debug recent mixing issues.  Will you be able to download and test a pre-release version, when we'll fix this?

**Comment by akhavr** [comment]
Can you post the content of your "Info" tab in "PrivateSend" dialog?

**Comment by anondashuser** [comment]
Hello,
sorry for my late answer. I really could not do it earlier. Here is the Info Tab you requested:
PrivateSend transactions count: 2606
Removed PrivateSend transactions count: 0
ps_denoms count: 1596
ps_spent_denoms count: 6901
ps_spending_denoms count: 0
ps_collaterals count: 0
ps_spent_collaterals count: 177
ps_spending_collaterals count: 0
ps_others count: 0
ps_spent_others count: 0
Reserved addresses count: 905
New denoms workflow data exists

Regarding downloading and testing pre-release I can try,
but I am limited by a lack of time as I just unfortunately lately demonstrated. Plus I lack the facility to have a proper test site which would take me really too much time to set up. And I don't think it is wise to test programs on the main account. In any case if you really need it, I can try to set up a new account on a different computer, and test it there. But it might work or not work independently to the main account one.

**Comment by zebra-lucky** [comment]
Possibliy fixed in #261
> New denoms workflow data exists

**Comment by anondashuser** [comment]
> Possibly fixed in #261

Thanks. I am right now using 4.0.9.4
Should I download 4.1.2.1 or would this fix not be there? Please let me know so I can tell you if the issue has been fixed. Thanks for your work.

**Comment by zebra-lucky** [comment]
#261 merged after 4.1.2.1 and will be in upcoming 4.1.2.2 release

**Comment by anondashuser** [comment]
Thanks. Looking forward for it.

**Comment by zebra-lucky** [comment]
> Thanks. Looking forward for it.

Please! Release 4.1.2.2 is available. Need to check if problem is fixed.

**Comment by anondashuser** [comment]
Wonderful, issue solved.
Thanks

**Comment by zebra-lucky** [comment]
> Wonderful, issue solved.
> Thanks

Thank you for check!
