### ISSUE TITLE
Adding Kraken as a source of pulling the prices from.

### ISSUE THREAD

**Issue by splawik21** [akhavr/electrum-dash#277]
Possible to add kraken.com as a source of data. So far only coingecko is available.
<img width="602" alt="image" src="https://user-images.githubusercontent.com/14001049/123959659-b5a5a200-d9ae-11eb-9e59-c807894a781d.png">

**Comment by zebra-lucky** [comment]
Looking for API (on Dash USD pair):

For current price:
https://api.kraken.com/0/public/Ticker?pair=DASHUSD
Seems `c` value (last trade closed) can be used.

For history data:
https://api.kraken.com/0/public/OHLC?pair=DASHUSD
Seems fifth array element (close price of interval) can be used.
