### ISSUE TITLE
Feature request: Use trezord PIN cache

### ISSUE THREAD

**Issue by xcelente** [akhavr/electrum-dash#291]
For many trezor desktop apps, the PIN is cached so that you don't have to re-enter it if you've only recently done it. Dash Electrum doesn't seem to use that cache, thus changing to a different wallet requires me to enter the PIN again, even if I only recently did it.

**Comment by zebra-lucky** [comment]
> I quit the app, restart immediately and it's asking me for the PIN again.

In electrum code during wallet close trezor plugin session
is cleared and LockDevice command is sent to Trezor.
This is done for security reasons.

GUI option can be added to trezor settings to not clear session
on wallet close (default off). It will be enabled on separate wallet.

This solution is what is need?

**Comment by xcelente** [comment]
I appreciate this is for security reasons but in my particular case I'm often switching between wallets and I'm the only user of the device.

Consider, for example, how someone uses a trezor with DeFi.  They can authenticate with. say, MEW and then when they use Kyber Network, they don't need to re-authenticate so long as the trezord session hasn't timed out.  My expectation is that trezord manages the timeout. It's a similar situation with gpg, I expect gpg-agent to manage the timeout and I have a separate kill switch if I want to immediately kill the gpg-agent process.

**Comment by zebra-lucky** [comment]
I will add option to electrum trezor settings (off by default),
which allow exit electrum app without locking trezor device.

**Comment by xcelente** [comment]
Thank you.
