### ISSUE TITLE
Ledger Device does not display / ask for the transaction confirmation OR nothing happens after ledger confirmation is made

### ISSUE THREAD

**Issue by S-BOS** [akhavr/electrum-dash#304]
Hello there,

I recently downloaded and installed succesfully on Windows 7 Pro the latest version of electrum-dash-wallet for windows 32 bits (version 4.1.5.0), in order to send some Dash coins from my Ledger Nano S to my Binance Wallet address starting by X**************. 
Before hand, I checked that Network was ok, that I was connected to a few Nodes ( 3 to 5)

**1st attempt**

> After pressing "Pay", choosing an average ETA fee, and pressing " Send", a small window appears with a message "Signing Transaction".
> Then an another windows appear with message "confirm transaction on your Ledger Device".
> -->>Problem no confirmation message on the Ledger device (even after 1 hour).
> So I finally press ESC to cancel the transaction.

![Electrum message 1st attempt](https://user-images.githubusercontent.com/97792048/149624351-c9108d7e-3a47-4371-870a-47d58473d5bb.PNG)

**2nd attempt**

> After pressing "Pay", choosing an average ETA fee, and pressing " Send", a small window appears with a message "Signing Transaction".
> I then review it and confirm it on my ledger device (first time).
> -->>Then nothing (even after 1 hour).

![Electrum message 2nd attempt](https://user-images.githubusercontent.com/97792048/149624347-123d9b38-2e53-4539-a9b4-9d9e3fe13da1.PNG)

I did several attempts, I did not succeed to repeat the 2nd attempt, I only manage to reproduce the 1st attempt.

I hope this will help you to track down this issue.  Do not hesitate if you have any question or if you want me to experiement more.

Kind Regards,

SBO

**Comment by zebra-lucky** [comment]
I'll try to reproduce the problem on fresh firmware.

**Comment by zebra-lucky** [comment]
Checked signing of transactions on 2.1.0 firmware/app versions.
Possible cause of slow reaction from HW is large amount of inputs.

**Comment by S-BOS** [comment]
Precision:  my Ledger Nano S has the Firmware 2.1.0 with Dash (DASH) app Version 2.0.1

**Comment by zebra-lucky** [comment]
Can you see estimate number of inputs in the transaction?
("Advanced" button in "Сonfirm Transaction" dialog show tx details)

Maybe count of inputs is too large and time of reaction is too long.
On 86 inputs time of device reaction is about 80 seconds.
If count of inputs too large, then possibly device timeouts
(default is 10 minutes) is involved someway.

**Comment by S-BOS** [comment]
The number of inputs is 309.

![Electrum Transaction number of inputs](https://user-images.githubusercontent.com/97792048/151226677-e67b2236-35f4-462b-bede-65ad549564f1.PNG)

**Comment by zebra-lucky** [comment]
I'll try to reproduce signing with this count of inputs.

As a workaround you can try to select separete inputs to spend,
selecting coins in coins tab (enabled from view -> coins menu),
to reduce reaction time.

**Comment by zebra-lucky** [comment]
I've tested signing transaction with 316 inputs.
This takes about 40 minutes before question about confirmation.
But i've disabled all timeouts on device.

You still can group coins to spend to form transactions with less count of inputs.

**Comment by S-BOS** [comment]
May I ask how did you disable "timeouts on device" ?

**Comment by zebra-lucky** [comment]
Not sure it's make effect

device main menu -> security -> [PIN lock, Screen saver]

**Comment by zebra-lucky** [comment]
You can enable coins tab (from main view menu) and select coins to spen with right mouse button.
This can help to spen what is you selected, instead all heap.

**Comment by zebra-lucky** [comment]
device main menu -> settings -> security -> [PIN lock, Screen saver]

**Comment by S-BOS** [comment]
So I selected roughly half the coins, clicked right then Spend.
I got a " Coin control active: 171 outputs available (309 total), 6.74484137 DASH "
After I went to the Send tab, entered the destination address, unclicked private send.
For the dash amount, I put MAX 6.74458785 DASH.
Then I pressed PAY.

In the transaction window pop up, I have left the default Fee: 0.00025352 DASH  ( 1000. duffs/kB ) and pressed FINALIZE.
Then I pressed SIGN.
After 10s, the message "confirm the transaction on device" pop-up appears, but nothing on device to confirm.

**Comment by zebra-lucky** [comment]
> After 10s, the message "confirm the transaction on device" pop-up appears, but nothing on device to confirm.
I've not checked on this count of inputs, but this can make a time.

**Comment by zebra-lucky** [comment]
I'll additionally check on windows host, possibly some OS specific.

**Comment by S-BOS** [comment]
I believe it worked with fewer inputs /coins (Coin control active: 34 outputs available (309 total), 1.45383915 DASH).
But on 1 address a different color code appeared.
![Electrum Transaction 34 inputs](https://user-images.githubusercontent.com/97792048/151445229-36ade307-87f8-4c0b-9cd0-5b1af4915ab5.PNG)

Do you know how long would it take to appear in the receivent wallet address?

**Comment by zebra-lucky** [comment]
It's a change address from separate diapason of addresses, used
to receive rest of amount of inputs, when you send some coins.

For example you have inputs A, B, C with total amount 1.1 Dash,
then you send some amount (say 0.7 Dash) to address X. Rest of
0.4( minus transaction fee) is sent to next free change address.

You can see addresses usage from addresses tab
(enabled from the View main menu).

**Comment by S-BOS** [comment]
I managed to do a 2nd transaction with the rest of the 309 inputs/coins.
You were right, depending on the number of inputs, there is a delay (15s for 30 inputs, maybe 40 minutes for 300 inputs), between Electrum pop-up asking to "confirm the transaction on device", and the actual confirmation to appear on the device.
I thank you Zebra-lucky for your help and support.

**Comment by zebra-lucky** [comment]
Ок, please!

Then I cancel testing on the win platform, seems time is similar.

**Comment by zebra-lucky** [comment]
> Maybe in the next version of Electrum, a warning could be added, so that users "like me", do not panic and wait long enough for confirmation to appear on device. As well as a message to invite them to disable "timeouts on device" device main menu -> security -> [PIN lock, Screen saver].

Need to consider, possibly estimate the number of inputs to show wraning.
