### ISSUE TITLE
Trezor support is broken in 3.1.3 Windows builds

### ISSUE THREAD

**Issue by jcrona** [akhavr/electrum-dash#37]
Support for the Trezor HW wallets is broken in 3.1.3 Windows builds (but works in 3.0.6.3).

I guess this is because the current version of Trezorlib uses bytes formatting which is only allowed in python 3.5 and above.
Using python 3.4, you get: unsupported operand type(s) for %: 'bytes' and 'bytes'.

The current version of Electrum already uses python 3.5 in Windows builds, so I would suggest to upgrade python in the wine docker from 3.4 to 3.5.

**Comment by akhavr** [comment]
The next build we will do with python 3.5

**Comment by akhavr** [comment]
Reopen if there's still an issue.
