### ISSUE TITLE
Sweeping paper wallet has error

### ISSUE THREAD

**Issue by npudar** [akhavr/electrum-dash#41]
Version 3.2.2
Trying to sweep a paper wallet. Asked for password to proceed. Get the error:

argument1: <class 'OverflowError'>: int too long to convert

Not sure how to proceed.

**Comment by akhavr** [comment]
Can you provide more details?  Is it a dialog or a trace in a console?  Which OS are you using?

**Comment by npudar** [comment]
Using Windows 10, 64bit
Upon pressing button to enter the password when asked (during sweep procedure), a dialog box popped up with the error code.
This occurred with both the testnet and the live network attempts to sweep a paper wallet.
Thanks

**Comment by akhavr** [comment]
Should be fixed in #42

**Comment by akhavr** [comment]
Fixed in 3.2.2.1 release
