### ISSUE TITLE
Invalid coin name

### ISSUE THREAD

**Issue by rockandruby** [akhavr/electrum-dash#44]
If use trezor(1.6.2 firmware) I get above error. After debug I found out that instead 
`def get_coin_name(self):
        return "DashTestnet" if constants.net.TESTNET else "Dash"`
should be
`def get_coin_name(self):
        return "Dash Testnet" if constants.net.TESTNET else "Dash"`
so add space between Dash Testnet

**Comment by akhavr** [comment]
Will be fixed in 3.2.3 release (or in `master`)
