### ISSUE TITLE
FUNDS ARE TRAPPED! Overflow error when sending

### ISSUE THREAD

**Issue by FabioLebbink** [akhavr/electrum-dash#46]
Error: 
Argument 1: <class 'OverflowError'>: int too long to convert

When trying to send funds to any address, this pops up after entering my password for verification!

**Comment by PastaPastaPasta** [comment]
Maybe try using a different version 3.0.6 was very stable for me

**Comment by akhavr** [comment]
Please, make sure that you're using the latest version - 3.2.2.1

If that doesn't help, please, reopen and add information about your platform.

Thanks
