### ISSUE TITLE
Ledger Nano S not properly recognized, not possible to confirm transaction

### ISSUE THREAD

**Issue by jamiemirror** [akhavr/electrum-dash#50]
Hi,
my Ledger Nano S wallet was recognized as generic Ledger only. 
The basic access, using DASH application on the wallet and Electrum 3.2.2.1 was fine, but when I decided to send some dash, Electrum application stuck on confirmation pop-up, waiting the Ledger wallet to confirm transaction. However no notification was shown on Ledger display, hence no transaction can be made.

Best regards

**Comment by akhavr** [comment]
Ok, problem confirmed.  We're working to fix this.

**Comment by PanderMusubi** [comment]
What is the progress?

**Comment by akhavr** [comment]
Should be fixed now.  At least, it works for me.  Reopen with more details, if it fails for you.
