### ISSUE TITLE
MasternodeConfig ISSUE

### ISSUE THREAD

**Issue by m0r4k** [akhavr/electrum-dash#58]
I have no Idea if somebody else is having the same problem but if I'm importing the masternode.conf the already activated MNs never go in enabled and announced state - except you are reactivating the MN!

I've had a quick and dirty fix - but there must be a better and more clean way!

```python
#FILE masternode_manager.py
#...
   def subscribe_to_masternodes(self):
        for mn in self.masternodes:
            #FIXME ugly -> very ugly#
            if not mn.announced:
                ## FIXME DELETE START ###
                collateral = mn.get_collateral_str()
                req = ('masternode.subscribe', [collateral])
                self.wallet.network.send([req], self.masternode_subscription_response)

                if len(collateral.split('-')[0]) == 64:
                    mn.announced = True
                    self.save()
                ### FIXME DELETE END ###
                continue

            collateral = mn.get_collateral_str()

            if self.masternode_statuses.get(collateral) is None:
                req = ('masternode.subscribe', [collateral])
                self.wallet.network.send([req], self.masternode_subscription_response)
                self.masternode_statuses[collateral] = ''
#...
```

**Comment by akhavr** [comment]
@m0r4k can you confirm that #60 works for you?

If not, please reopen with more details.

**Comment by m0r4k** [comment]
It is working perfect but the announced bit is not set! Which is actually
true because you did not announce it to network :)

in console the command
>> showmasternode('default')
shows announced "false" and will fillup the "last_ping" options only if you
announce the masternode over electrum

But for shure this is much better than before




____________________

Daniel Morak

Trade4Fun

morak.daniel@gmail.com

mor4k@outlook.com

________________________________
Von: akhavr <notifications@github.com>
Gesendet: Samstag, 3. November 2018 18:09
An: akhavr/electrum-dash
Cc: z3r0; Mention
Betreff: Re: [akhavr/electrum-dash] MasternodeConfig ISSUE (#58)


Closed #58<https://github.com/akhavr/electrum-dash/issues/58>.

**Comment by m0r4k** [comment]
It is working perfect but the announced bit is not set! Which is actually
true because you did not announce it to network :)

in console the command
> showmasternode('default')
shows announced "false" and will fillup the "last_ping" options only if you
announce the masternode over electrum

But for shure this is much better than before

**Comment by akhavr** [comment]
I'm not sure it's a good idea to reannounce existing masternode to the network: this will kick it down to the bottom of the payment list.

**Comment by m0r4k** [comment]
yes you are right -> reannouncement is a bad idea because of the ranking list back ranking
what I mean is the last_ping fillup in the kind of "pseudo announcement"

I'll detail my thoughts when I'm less busy
