### ISSUE TITLE
Can't make any transactions

### ISSUE THREAD

**Issue by mangus** [akhavr/electrum-dash#64]
Just installed the application with _add-apt-repository_ (so version 3.2.3.2) but can't make any transactions:
I can fill in the "send" form but after clicking "send" button I get an error message:

> 'Transaction' object has no attribute 'tx_type'

**Comment by mangus** [comment]
I downloaded the 3.2.3.1 version and that one works well.

**Comment by ec1warc1** [comment]
A user from Venezuela is reporting this same message on a 32 bit windows machine:
![image](https://user-images.githubusercontent.com/23389201/50809070-7ca18080-12cf-11e9-90a4-6b2bea6c4d88.png)

**Comment by ec1warc1** [comment]
I got the same error on my computer! 
![image](https://user-images.githubusercontent.com/23389201/50838257-98d30b00-132b-11e9-8d9c-11563055e79d.png)

**IMPORTANT:** This is fixed by upgrading to 3.2.4 - awesome! Thanks!
