### ISSUE TITLE
no usable servers

### ISSUE THREAD

**Issue by molecular** [akhavr/electrum-dash#72]
After removing "recent_servers" file and startup, I get 2 servers in the server list on network tab:

 * 128.62.234.69
 * electrum.dash.siampm.com

On overview tab of network dialog I see "blockvhain: -1 blobks", so i assume those servers don't work?

Is there a list of wokring servers somewhere?

**Comment by akhavr** [comment]
I guess this was solved already.  Reopen if not

**Comment by funny-falcon** [comment]
I have just downloaded and run electrum-dash. It has couple of servers configurred: drk.p2pay.com and electrum.dash.siampm.com . Both are not available for connecting at port 50002 at the moment.
Does it mean I could not use electrum-dash ?

**Comment by funny-falcon** [comment]
It is not available neither through tor nor through vpn.

**Comment by funny-falcon** [comment]
hmm... electrum.dash.siampm.com is available to connect to. But electrum-dash doesn't try to connect.

**Comment by akhavr** [comment]
Try once again, please?

**Comment by funny-falcon** [comment]
Yes, it works at the moment. Unfortunately, I've moved to exodus due to issue.
Is there a way to help electrum-dash with servers?
I certainly like to use open-source software (and I didn't moved btc and ltc to exodus from its electrum wallets), but it have to be usable.

**Comment by akhavr** [comment]
You can run your own ElectrumX server :)

Just run a full dash node plus current https://github.com/kyuupichan/electrumx
It doesn't requires much CPU or RAM.

If you're going to do this, let me know the server address and we'll include it in the next release
