### ISSUE TITLE
Unsigned Windows executables

### ISSUE THREAD

**Issue by jesobreira** [akhavr/electrum-dash#79]
I've noticed that the Windows version installer and also the installed executable files aren't signed.

Was it supposed to be signed? Should I trust the installer downloaded at electrum.dash.org today (March 29th 2019)?

**Comment by akhavr** [comment]
No, it isn't supposed to be signed.  You can verify the authenticity by comparing the signatures, which are downloadable at https://github.com/akhavr/electrum-dash/releases/tag/3.2.5.1

Reopen the issue if you need more help.
