### ISSUE TITLE
[BUG] When I click the back button, the application crashes and stops responding.

### ISSUE THREAD

**Issue by sargoon** [akhavr/electrum-dash#88]
Hi there @akhavr 

Actual behavior

When I click the back button, the application crashes and stops responding.

How to reproduce

1. Open the Dash Electrum app.
2. Select any of the 3 options.
3. When you click the back button of your device, then you will see the screen freezes and the application stops responding.

• App version: 3.3.6.0 (latest)
• Operating system: Android 9.0

Recording Of The Bug
![dashelectrum](https://user-images.githubusercontent.com/34961616/60946530-1f769e00-a2f7-11e9-9822-b2b4d9f18fef.gif)

**Comment by sargoon** [comment]
Are you there @akhavr?

**Comment by akhavr** [comment]
Was travelling (with issues).  We've reproduced this defect and it's in the development queue.
