### ISSUE TITLE
Please make it available as Flatpak package

### ISSUE THREAD

**Issue by Nokia808** [akhavr/electrum-dash#92]
Hi. It is nice to make this wallet available on Flathub as a flatpak package. This way, it will be available for almost all Linux users.

Yes, you provide AppImage package, which also a universal Linux package, but flatpak is too much more secure & convenient ......

Best.

**Comment by taw00** [comment]
Flatpak is certainly the better container-ish packaging format. I am entertaining building this myself. I will post here if I do.

Note: I build RPMs for dash-electrum here, if that is your cup of tea: https://github.com/taw00/electrum-dash-rpm/

**Comment by Nokia808** [comment]
@taw00 
Hi. Thank you for your interest ! Regarding your .rpm package, I opened an issue within it's repository on GitHub.

If you added this wallet, as flatpak, to FlatHub you will really make Dash easily available for almost all Linux distros. ....... I will wait this.

**Comment by Nokia808** [comment]
Hi. I would like to bring your attention to the fact that "Electrum Bitcoin wallet" already existing as flatpak in FlatHub - see:
https://github.com/flathub/org.electrum.electrum

Please see it's pull request that already merged:
flathub/flathub#1102

The above link will help you too much when you package Electrum DASH as flatpak for FlatHub. It will assist you to abbreviate the way by avoiding you from mistakes that already done during original packaging PR - see:
flathub/flathub#837

**Comment by taw00** [comment]
I'll take a look when I have more time. Thanks.

**Comment by akhavr** [comment]
@taw00 if you'd submit PR for your rpm and flatpak build scripts for Travis - we will merge them after review and they will be delivered automagically at each release :)

**Comment by Nokia808** [comment]
@taw00 
@akhavr 
Hi. The electrum groestlcoin wallet now available on FlatHub as flatpak - see the following PR (which is already merged):
flathub/flathub#1506

Repository had been created- see:
https://github.com/flathub/org.groestlcoin.electrum-grs

This is 2nd electrum wallet, after electrum Bitcoin wallet, that became available as flatpak package on FlatHub.

Hope this will help you ...

**Comment by taw00** [comment]
@Nokia808 Thanks. That will likely help. If only I had the cycles to work on it right now. :/

**Comment by zebra-lucky** [comment]
I'll make PR to flathub in the near future.

Looking at already merged PR for btc electrum:
https://github.com/flathub/flathub/pull/1102

**Comment by zebra-lucky** [comment]
Added PR to flathub:
https://github.com/flathub/flathub/pull/1536

**Comment by zebra-lucky** [comment]
It's desirable to app appdata XML to project (as suggested in https://github.com/flathub/flathub/pull/1536). I'll add metadata in https://github.com/akhavr/electrum-dash/pull/117 .

**Comment by Nokia808** [comment]
@zebra-lucky 
@taw00 
@akhavr 
Thank you too much ! You strengthen FlatHub & elevate it up by this work ! This will stimulates other cryptocurrencies wallet to join flatpak on FlatHub, making by this usage of cryptocurrencies much easier, convenient & SECURE for Linux users
