### ISSUE TITLE
Not connected(proxy enabled)

### ISSUE THREAD

**Issue by dobcrypto** [akhavr/electrum-dash#97]
Have 8 peers online, Receive and Sent KiB, but "Not connected" anyway =(
With TOR proxy or without proxy, same "Not connected".

**Comment by zebra-lucky** [comment]
Hi!

Dash Electrum currently have two type of network connections.
One for Electrum protocol (Network button), which syncronizes
transactions data, and one optional P2P network (Dash Network
button) for Dash specific features as InstantSend.

"Not connected" in status bar is related to main electrum Network,
sou you should check network button in status bar, and Electrum
protocol related connections.

**Comment by dobcrypto** [comment]
@zebra-lucky strange... 
dunno what was a problem, but today wallet starts without problem/connection issue.
